name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🧰 Maintenance
    label: chore
tag-template: - $TITLE @$AUTHOR (#$NUMBER)
template: |
  ## Changes

  $CHANGES

  ## 🕵️ Full commit logs

  https://github.com/mskcc/cmo-metadb-common/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
